name: simple_sse workspace

packages:
  - packages/*

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  analyze: melos exec -- dart analyze .
  format: melos exec -- dart format .
  test: melos exec -- dart test .
  publish:dry: melos exec -- dart pub publish --dry-run